### ISSUE TITLE
maven central repo

### ISSUE THREAD

**Issue by Eljah** [marre/smsj#2]
Hi! Could you add the smsj library to tht Maven Central Repo?

**Comment by xfslove** [comment]
There is a PR #3. It contains several bug fixes, and has been generally refactored, and released at maven central repository.

**Comment by marre** [comment]
See @xfslove comment above.

```
<dependency>
    <groupId>com.github.xfslove</groupId>
    <artifactId>smsj</artifactId>
    <version>1.0.0</version>
</dependency>
```
